Build:
	gcc test.c ../unity/unity.c -I../unity ../inc/all_functions.h -I../inc ../src/new_reg_tax.c ../src/old_reg_tax_less60.c ../src/old_reg_tax_more60.c ../src/old_reg_tax_more80.c -I../src

Run:
	./a.exe	